// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: protobuf/hyper.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HyperClient is the client API for Hyper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperClient interface {
	// client sends a request to the server and receives a response
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	// client sends a response to the server and receives an acknowledgment
	ServerCall(ctx context.Context, opts ...grpc.CallOption) (Hyper_ServerCallClient, error)
}

type hyperClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperClient(cc grpc.ClientConnInterface) HyperClient {
	return &hyperClient{cc}
}

func (c *hyperClient) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Hyper/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperClient) ServerCall(ctx context.Context, opts ...grpc.CallOption) (Hyper_ServerCallClient, error) {
	stream, err := c.cc.NewStream(ctx, &Hyper_ServiceDesc.Streams[0], "/Hyper/ServerCall", opts...)
	if err != nil {
		return nil, err
	}
	x := &hyperServerCallClient{stream}
	return x, nil
}

type Hyper_ServerCallClient interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ClientStream
}

type hyperServerCallClient struct {
	grpc.ClientStream
}

func (x *hyperServerCallClient) Send(m *Response) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hyperServerCallClient) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HyperServer is the server API for Hyper service.
// All implementations must embed UnimplementedHyperServer
// for forward compatibility
type HyperServer interface {
	// client sends a request to the server and receives a response
	Call(context.Context, *Request) (*Response, error)
	// client sends a response to the server and receives an acknowledgment
	ServerCall(Hyper_ServerCallServer) error
	mustEmbedUnimplementedHyperServer()
}

// UnimplementedHyperServer must be embedded to have forward compatible implementations.
type UnimplementedHyperServer struct {
}

func (UnimplementedHyperServer) Call(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedHyperServer) ServerCall(Hyper_ServerCallServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerCall not implemented")
}
func (UnimplementedHyperServer) mustEmbedUnimplementedHyperServer() {}

// UnsafeHyperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperServer will
// result in compilation errors.
type UnsafeHyperServer interface {
	mustEmbedUnimplementedHyperServer()
}

func RegisterHyperServer(s grpc.ServiceRegistrar, srv HyperServer) {
	s.RegisterService(&Hyper_ServiceDesc, srv)
}

func _Hyper_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Hyper/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hyper_ServerCall_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyperServer).ServerCall(&hyperServerCallServer{stream})
}

type Hyper_ServerCallServer interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ServerStream
}

type hyperServerCallServer struct {
	grpc.ServerStream
}

func (x *hyperServerCallServer) Send(m *Request) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hyperServerCallServer) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Hyper_ServiceDesc is the grpc.ServiceDesc for Hyper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hyper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Hyper",
	HandlerType: (*HyperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Hyper_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerCall",
			Handler:       _Hyper_ServerCall_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/hyper.proto",
}
