vars:
  OP:
    source: env
    variable: HYPER_OP
    default: quic-1
    type: string
name: $OP
directory:
  type: api
  settings:
    jsonrpc_client:
      tls:
        certificate_file: "/$DIR/../../certs/$OP.crt"
        key_file: "/$DIR/../../certs/$OP.key"
        ca_certificate_files: ["/$DIR/../../certs/root.crt"]
    ca_certificate_files: ["/$DIR/../../certs/root.crt"]
    ca_intermediate_certificate_files: ["/$DIR/../../certs/intermediate.crt"]
    endpoints: ["https://localhost:3322/jsonrpc"]
    server_names: ["sd-1"]
channels: # defines all the channels that we want to open when starting the server
  - name: main QUIC client/server # forwards TCP streams and UDP packets via QUIC
    type: quic
    settings:
      bindAddress: localhost:7771
      channels:
        - remote:
            host: quic-2
            port: 4444
          local:
            port: 5555
      tls:
        ca_certificate_files: ["/$DIR/../../certs/root.crt"]
        certificate_file: "/$DIR/../../certs/$OP.crt"
        key_file: "/$DIR/../../certs/$OP.key"
