name: Publish docker images

on:
  push:
    tags:
      - v*.*.*

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Extract version
        run: echo VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV
      - name: Check output
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo $VERSION
          echo ${{ env.VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Create Hyper image tag
        id: meta_hyper
        uses: docker/metadata-action@v3
        with:
          images: kiprotect/hyper
      - name: Build Hyper
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Eps.dockerfile
          tags: ${{ steps.meta_hyper.outputs.tags }}
          push: true
          labels: |
            kiprotect.hyper.image.revision=${{ github.sha }}
      - name: Create sd image tag
        id: meta_sd
        uses: docker/metadata-action@v3
        with:
          images: kiprotect/hyper-sd
      - name: Build sd
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Sd.dockerfile
          tags: ${{ steps.meta_sd.outputs.tags }}
          push: true
          labels: |
            kiprotect.hyper-sd.image.revision=${{ github.sha }}
      - name: Create proxy image tag
        id: meta_proxy
        uses: docker/metadata-action@v3
        with:
          images: kiprotect/hyper-proxy
      - name: Build proxy
        uses: docker/build-push-action@v2.9.0
        with:
          build-args: VERSION=${{ env.VERSION }}
          file: ./docker/Proxy.dockerfile
          tags: ${{ steps.meta_proxy.outputs.tags }}
          push: true
          labels: |
            kiprotect.hyper-proxy.image.revision=${{ github.sha }}
